### ISSUE TITLE
runtest error

### ISSUE THREAD

**Issue by tianxingyzxq** [DaleSong89/caffe-mt#3]
Hi, I got the following error when I run test the code on ubuntu 14.04. Can anybody help?
[ RUN      ] LocalConvolutionLayerTest/2.TestLocalConvolution
F1107 15:15:44.629595 13247 blob.hpp:173] Check failed: indices[i] < shape(i) (1 vs. 1) 
*** Check failure stack trace: ***
    @     0x2b022ededdbd  google::LogMessage::Fail()
    @     0x2b022edefc5d  google::LogMessage::SendToLog()
    @     0x2b022eded9ac  google::LogMessage::Flush()
    @     0x2b022edf057e  google::LogMessageFatal::~LogMessageFatal()
    @           0x6f5879  caffe::caffe_conv<>()
    @           0x732056  caffe::caffe_loc_conv<>()
    @           0x737645  caffe::LocalConvolutionLayerTest_TestLocalConvolution_Test<>::TestBody()
    @           0x90f8e3  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x9065c7  testing::Test::Run()
    @           0x90666e  testing::TestInfo::Run()
    @           0x906775  testing::TestCase::Run()
    @           0x909ab8  testing::internal::UnitTestImpl::RunAllTests()
    @           0x909d47  testing::UnitTest::Run()
    @           0x46edbf  main
    @     0x2b0232455f45  (unknown)
    @           0x476ab9  (unknown)
make: *** [runtest] Aborted (core dumped)

**Comment by knsong** [comment]
@tianxingyzxq  I've fixed them, please pull and try again : )

**Comment by tianxingyzxq** [comment]
I have tried again using git pull, but I still have the same problem as above.

**Comment by knsong** [comment]
@tianxingyzxq What I've fixed are some compilation errors. For the runtest error, you should provide some info about the caffe you used as I mentioned in the email.

**Comment by knsong** [comment]
@tianxingyzxq

**Comment by tianxingyzxq** [comment]
Yes，I see. but I am using the caffe you provide. did I missing anything? @knsong

**Comment by tianxingyzxq** [comment]
I have compile this latest code using two ubuntu 14.04 machine and get the same problem. @knsong

**Comment by knsong** [comment]
@tianxingyzxq  Are you using the version @37b1725?

**Comment by tianxingyzxq** [comment]
Yes, 
![default](https://cloud.githubusercontent.com/assets/5278803/20082429/b3866d76-a590-11e6-8c3b-365be6adde38.PNG)

**Comment by tianxingyzxq** [comment]
because other tests have passed well, I think the problem may arise in the local_conv_layer. @knsong

**Comment by knsong** [comment]
@tianxingyzxq Please also provide the compilation errors.

**Comment by tianxingyzxq** [comment]
Compilation is ok now. The error occurs in the test_local_conv_layer.cpp. @knsong

**Comment by knsong** [comment]
@tianxingyzxq Test for local_conv_layer is also ok here.

**Comment by tianxingyzxq** [comment]
Test for local_conv_layer is ok in windows 7. But It is not ok in ubuntu. @knsong

**Comment by knsong** [comment]
@tianxingyzxq  But I tested it on ubuntu.

**Comment by Banus** [comment]
@tianxingyzxq, I noticed that there is a name collision on `caffe_conv` behind the problem. If you run the standalone test `.build_release/test/test_local_convolution_layer.testbin` it runs fine. You only need to rename that function.

I created PR #4 to fix the problem.

**Comment by knsong** [comment]
Have merged it and thank you for the work. @Banus @tianxingyzxq

**Comment by tianxingyzxq** [comment]
Problem solved, thanks. @knsong @Banus
